### PR TITLE
Create and Implement Spinner

### PR DESCRIPTION
**Pull request by gatorjuice**
## Proposed changes

This adds a spinner component that can be added anywhere and responds to the state of loading in the store.

https://user-images.githubusercontent.com/11019755/147841355-e3a8731b-61a9-41ac-a710-6b174218e4c5.mov

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Refactor (found a better way to write the code and accomplish the same task)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by pgeliebter — COMMENTED** [review]
Can this spinner be used on sub components? Like let's say there are a bunch of cards on a page and they have different data sources. Right now it seems that the spinner will only be a page wide one.

**Comment by gatorjuice** [comment]
> Can this spinner be used on sub components? Like let's say there are a bunch of cards on a page and they have different data sources. Right now it seems that the spinner will only be a page wide one.

That’s a REALLY great question. Fortunately, this component is not a full screen overlay (i should change the branch name) it’s just inside div and it would render in line wherever you put it. I had intended that we could modify it in the future with color and size props so it can literally go on an individual p line.

**Comment by gatorjuice** [comment]
Also, I think you're saying that since it responds to loading state directly that it's a bit limited. Maybe it should accept an `active` prop or something?

**Review by pgeliebter — COMMENTED** [review]
looks good

**Review by pgeliebter — APPROVED** [review]
looks good #2

**Pull request merged**
